# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aboutform.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(800, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(widget.sizePolicy().hasHeightForWidth())
        widget.setSizePolicy(sizePolicy)
        widget.setMinimumSize(QtCore.QSize(800, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sus1/sus/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        widget.setWindowIcon(icon)
        widget.setStyleSheet("*{font: 12pt \"More Perfect DOS VGA\"; color: white; selection-color: rgb(0, 0, 0); selection-background-color: rgb(255, 255, 255);}\n"
"*:disabled{color:gray}\n"
"\n"
"QWidget{background-color:black;}\n"
"\n"
"QCheckBox{ background-color: rgb(0, 0, 0);}\n"
"QCheckBox:indicator { border: 2px solid gray; background: none;}\n"
"QCheckBox:indicator:hover { border: 2px solid white; background: none;}\n"
"QCheckBox:indicator:checked { border: 3px solid white; background: none;}\n"
"QCheckBox:indicator:disabled { border: 2px solid gray}\n"
"QCheckBox:indicator:checked:disabled { border: 3px solid gray}\n"
"\n"
"QLineEdit{border: 1px solid white}\n"
"QLineEdit:disabled{border: 1px solid gray;}\n"
"\n"
"QScrollArea{ border: 1px solid white;}\n"
"\n"
"QLabel{border-color: white;}\n"
"\n"
"QPushButton { border: 1px double white;}\n"
"QPushButton:pressed { background-color: rgb(255, 255, 255); color:black;}\n"
"QPushButton:disabled { border: 1px double gray;}\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_title = QtWidgets.QLabel(widget)
        font = QtGui.QFont()
        font.setFamily("More Perfect DOS VGA")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("font: 16pt \"More Perfect DOS VGA\";")
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout_2.addWidget(self.lbl_title)
        self.pltxt = QtWidgets.QTextBrowser(widget)
        self.pltxt.setStyleSheet("border: 1px solid white;")
        self.pltxt.setObjectName("pltxt")
        self.verticalLayout_2.addWidget(self.pltxt)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "About"))
        self.lbl_title.setText(_translate("widget", "###ABOUT THIS THING###"))
